>> improve error-handling

diff --git a/yona b/yona
--- a/yona
+++ b/yona
@@ -175,8 +175,8 @@ case $1 in
     *) 
         LINE=$(grep "^$1 = " $YONA_FILE)
         if [[ -z "$LINE" ]]; then
-            echo "Yona Error: Undefined project command!"
-            return
+            echo "Yona Error: Undefined project command!" >&2
+            exit 1
         fi
         eval "${LINE#*= }";;
  esac
@@ -201,7 +201,8 @@ until [[ $(pwd) == / ]]; do
     fi
     cd ..
 done
-echo "Yona Error: No .yona file!"
+echo "Yona Error: No .yona file!" >&2
+exit 1
 }
 
 
